### ISSUE TITLE
Crashes on start

### ISSUE THREAD

**Issue by AndreKeks** [smellyriver/tankinspector#2] opened 2017-05-13 14:27 UTC
Crashes on start on Windows 10 x64 v.1703
Dump and sti.log:
https://drive.google.com/open?id=0BxhXJA5HRplSMWZ6bkpOWS04ajQ

**Comment by ghost** [comment] 2017-05-13 15:04
Try deleting the tankinspector map in <del>C://users/AppData</del> \AppData\Local\Smellyriver. Then start the program again. Make sure to direct the app to the right game map C://Games//World_of_Tanks_EU. Works for me.

If I try to direct the app to another game map like the Public Server (_ST) or the Sandbox server (_SB) then I get the startup error too. ;-)

**Comment by hillin** [comment] 2017-05-15 02:13
@AndreKeks thanks for the reporting, we are looking into it

**Comment by hillin** [comment] 2017-05-15 02:15
Unfortunately I cannot reproduce this issue on my side. Anyone encountering this issue and have the ability to debug, could you try to build from the source code and see what's happening?

**Comment by darkfuryXL** [comment] 2017-05-15 18:27
Hi Hillin.
Attached is my sti.log for the same issue. System is Win7 x64.
[sti.zip](https://github.com/smellyriver/tankinspector/files/1002021/sti.zip)

**Comment by ghost** [comment] 2017-05-16 14:48
Hi hillin,

i have same problem as AndreKeks.

Installed/unpacked version 1.8.0.200 on Win10 64bit v1703 Build 15063.296.
Right after start of EXE program crashes.

Attached is sti.log
[sti.zip](https://github.com/smellyriver/tankinspector/files/1004847/sti.zip)

**Comment by DrLivesey2** [comment] 2017-05-16 22:01
It also сrashes when you start, even without reaching the selection of the folder with the game
Installed/unpacked version 1.8.0.200 on Win7 64bit
P.S. The folder was deleted in C: // users / AppData \ AppData \ Local \ Smellyriver.

**Comment by DrLivesey2** [comment] 2017-05-16 22:06
It also сrashes when you start, even without reaching the selection of the folder with the game
Installed/unpacked version 1.8.0.200 on Win7 64bit
P.S. The folder was deleted in C: // users / AppData \ AppData \ Local \ Smellyriver.

Attached is sti.log -> sti.txt
[sti.txt](https://github.com/smellyriver/tankinspector/files/1005961/sti.txt)

**Comment by Zedd7** [comment] 2017-05-19 09:38
Exact same issue and conditions as DrLivesey2 but with Win10 x64
sti.txt : https://pastebin.com/hBqZ51cK

**Comment by Kronosaurus** [comment] 2017-05-20 09:13
I have crashes on 3 different machines with Windows 8.1 and Windows 10. It seems to hang with the .net framework together.

**Comment by ghost** [comment] 2017-05-20 10:07
@hillin: double checked all .Net installations, activated old .Net 2 and 3 and also ran Microsoft NetFxRepairTool... same behaviour as before:
Program runs a few seconds and tries to start (TankInspector logo can be seen), then error message pops up. :-(

**Comment by craenker** [comment] 2017-05-23 17:44
Had the same issue. Worked after compiling it by myself.

Never compiled anything before or even used Visiual Studio.

I did just downloaded and install it. Restored the package from nugget and compiled it. Didn't change anything. 

Win10 64bit

**Comment by hillin** [comment] 2017-05-24 11:56
Hi guys,

I've checked with the original code (which is a real mess, on whose base the open-sourced code is heavily re-organized), turns out I've missed an important workflow step, which updates all the localization files after build. So anyone using a system language other than English (American) will encounter this issue. 
I fixed this problem and made a new release. Please try it out here: https://github.com/smellyriver/tankinspector/releases/tag/1.8.1

This issue shoud be fixed with commit https://github.com/smellyriver/tankinspector/commit/a4965aa0704344b1dbad8d2fe85000b28033bfd8.

**Closed as completed by hillin** 2017-05-24 11:56 UTC
Labels: bug

**Comment by darkfuryXL** [comment] 2017-05-26 16:05
Hi hillin,
posting to confirm new version works great! 
I am indeed using PL version of Win7.
Thank you for update!

**Comment by hillin** [comment] 2017-05-26 16:28
@darkfuryXL good to know, have fun!
