### ISSUE TITLE
still crashes :/

### ISSUE THREAD

**Issue by WenoM97** [smellyriver/tankinspector#1] opened 2017-05-12 16:05 UTC
https://snag.gy/NFeiCI.jpg

**Comment by ghost** [comment] 2017-05-13 15:04
Try deleting the tankinspector map in <del>C://users/AppData</del> \AppData\Local\Smellyriver. Then start the program again. Make sure to direct the app to the right game map C://Games//World_of_Tanks_EU. Works for me.

If I try to direct the app to another game map like the Public Server (_ST) or the Sandbox server (_SB) then I get the startup error too. ;-)

**Comment by hillin** [comment] 2017-05-15 02:03
@WenoM97 Could you please post the **sti.log** file so I can diagnose?

**Comment by hillin** [comment] 2017-05-15 02:14
closed: duplicate of #2 
(Although this post appeared earlier, #2 has provided more information so I'm closing this one)

**Closed as completed by hillin** 2017-05-15 02:14 UTC
Labels: bug, duplicate
