### ISSUE TITLE
crashes

### ISSUE THREAD

**Issue by darkfuryXL** [smellyriver/tankinspector#3] opened 2017-05-13 14:59 UTC
Hi. I'm new here, but would like to help. 
I downloaded and installed latest STI today. Unfortunately this crashes seconds after start.
WoT version: 0.9.18.0 #427
System: Win7 x64

**Comment by ghost** [comment] 2017-05-13 15:03
Try deleting the tankinspector map in <del>C://users/AppData</del> \AppData\Local\Smellyriver. Then start the program again. Make sure to direct the app to the right game map C://Games//World_of_Tanks_EU. Works for me.

If I try to direct the app to another game map like the Public Server (_ST) or the Sandbox server (_SB) then I get the startup error too. ;-)

**Comment by darkfuryXL** [comment] 2017-05-13 15:14
RH-Code, thank you for prompt response. I am not sure however if I follow you. What am I suppose to delete?
I checked AppData folder. The only conten related to TI was found in \\AppData\Local\Smellyriver. I deleted 2 folders that were there.  Irestarted TI again but with same result as before = crash within 2 seconds.
I have only one version of WoT installed.

**Comment by ghost** [comment] 2017-05-13 15:52
Yeah ... that were the 2 folders I ment. If that doesn't help, I can't help you any further. Sorry.

**Comment by darkfuryXL** [comment] 2017-05-13 17:35
Thank you anyway.

**Comment by Nullmaruzero** [comment] 2017-05-13 20:58
I have had this problem with earlier versions too. Then deleting the SmellyRiver folder from AppData helped. The problem then started with some models being bugged, program was working until I clicked some tank aaaand boom, crash. Then it threw the error every time.
Later problem reoccured with a new patch (obviously, but back in the days it sometimes worked with new versions or just had some bugs, but not always crashing). The moment you tried to point the program to the new version (or other, like CT) it kept crashing.

Now though, I cannot make it work. Removing %AppData%/Smellyriver does not help.

So it has something to do with caching mechanism. This problem seems to be quite long-lasting throughout the versions so perhaps you guys could code some parameter to the .exe so people could reset the settings, ignore prefetched/cached data or launch the program in some sort of safe-mode.
I am pretty sure the problem lies somewhere there.

OS: Windows 10 64bit

**Comment by hillin** [comment] 2017-05-15 02:04
@darkfuryXL Could you please post the **sti.log** file so I can diagnose?

**Comment by hillin** [comment] 2017-05-15 02:14
Closed: duplicate of #2

**Closed as completed by hillin** 2017-05-15 02:14 UTC
Labels: bug, duplicate
